using System;

namespace DubuqueCodeCamp.Scheduler
{
    /// <summary>
    /// Class that represents all the data contained in the Proposed Schedule ListView
    /// </summary>
    public class TalkSession
    {
        /// <summary>
        /// Date of the event during which this TalkSession takes place
        /// </summary>
        public DateTime SessionDate { get; set; }

        /// <summary>
        /// Time this TalkSession begins
        /// </summary>
        public DateTime SessionStartTime { get; set; }

        /// <summary>
        /// Time this TalkSession ends
        /// </summary>
        public DateTime SessionEndTime { get; set; }

        /// <summary>
        /// Length of time in minutes that this TalkSession spans, generated by the database
        /// </summary>
        public int SessionLengthMinutes { get; set; }

        /// <summary>
        /// Name of the room this TalkSession will take place in
        /// </summary>
        public string RoomName { get; set; }

        /// <summary>
        /// Capacity of the room this TalkSession will take place in
        /// </summary>
        public int RoomCapacity { get; set; }

        /// <summary>
        /// Venue where this TalkSession will take place
        /// </summary>
        public string Venue { get; set; }

        /// <summary>
        /// Title of the talk for this TalkSession
        /// </summary>
        public string TalkTitle { get; set; }

        /// <summary>
        /// Summary of the talk for this TalkSession
        /// </summary>
        public string TalkSummary { get; set; }

        /// <summary>
        /// First name of the associated talk's speaker
        /// </summary>
        public string SpeakerFirstName { get; set; }

        /// <summary>
        /// Last name of the associated talk's speaker
        /// </summary>
        public string SpeakerLastName { get; set; }
    }
}
